In [2]:
## Import the libraries numpy,pandas,sklearn

import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn.metrics import accuracy_score

In [12]:
# load the data set
diabetes_data=pd.read_csv('E:\Applied AI related materials\Python notebooks\diabetes.csv')

In [15]:
diabetes_data.head(10) ## it gives the first 10 rows of the dataset

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
5,5,116,74,0,0,25.6,0.201,30,0
6,3,78,50,32,88,31.0,0.248,26,1
7,10,115,0,0,0,35.3,0.134,29,0
8,2,197,70,45,543,30.5,0.158,53,1
9,8,125,96,0,0,0.0,0.232,54,1

In [16]:
diabetes_data.tail(10) ## it gives the last 10 rows of the data set

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
758,1,106,76,0,0,37.5,0.197,26,0
759,6,190,92,0,0,35.5,0.278,66,1
760,2,88,58,26,16,28.4,0.766,22,0
761,9,170,74,31,0,44.0,0.403,43,1
762,9,89,62,0,0,22.5,0.142,33,0
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

In [11]:
diabetes_data.describe()   ##desribe the data and know about the statistics of data like mean, std etc.

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,3.845052,120.894531,69.105469,20.536458,79.799479,31.992578,0.471876,33.240885,0.348958
std,3.369578,31.972618,19.355807,15.952218,115.244002,7.884160,0.331329,11.760232,0.476951
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000,0.000000
25%,1.000000,99.000000,62.000000,0.000000,0.000000,27.300000,0.243750,24.000000,0.000000
50%,3.000000,117.000000,72.000000,23.000000,30.500000,32.000000,0.372500,29.000000,0.000000
75%,6.000000,140.250000,80.000000,32.000000,127.250000,36.600000,0.626250,41.000000,1.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000

In [24]:
diabetes_data['Outcome'].value_counts() ##counts the values of different datapoints in outcome column

0    500
1    268
Name: Outcome, dtype: int64

In [27]:
X=diabetes_data.drop(columns='Outcome', axis=1)   ## assign the features to the variabels
Y=diabetes_data['Outcome']

In [33]:
scaler=StandardScaler()                                           ##Call StandardScaler() function and assign to varaible
scaler.fit(X)                                                     ## fit the datset X to scaler function
standardized_data=scaler.transform(X)                              ## transform the datset X and standardized the dataset

In [35]:
X= standardized_data                   ## assign standardized data to variable X

In [38]:
##split the data in train and test data where 20 percent data reserve for test and randomize the data in terms of Y 

X_train, X_test, Y_train, Y_test=train_test_split(X, Y, test_size=0.2, stratify=Y, random_state=2)

In [40]:
## training the  SVM model 

classifier=svm.SVC(kernel='linear')
classifier.fit(X,Y)

SVC(kernel='linear')

In [41]:
## Now we check the accuracy of the model using train data

X_train_prediction=classifier.predict(X_train)
training_data_accuracy=accuracy_score(X_train_prediction,Y_train)

In [42]:
print('The accuracy of the model on training data is: ',training_data_accuracy)

The accuracy of the model on training data is:  0.7736156351791531

In [43]:
## Now we check the accuracy of the model using test data

X_test_prediction=classifier.predict(X_test)
test_data_accuracy=accuracy_score(X_test_prediction,Y_test)

In [44]:
print('The accuracy of the model on test data is: ',test_data_accuracy)

The accuracy of the model on test data is:  0.7727272727272727

In [51]:
## Predicting system

input_data=(5,117,92,0,0,34.1,0.337,38)
input_data_array=np.asarray(input_data)                                 ##input data as numpy array
input_data_reshaped=input_data_array.reshape(1,-1)                       ## reshape the array

In [52]:
std_data=scaler.transform(input_data_reshaped)                         # standardize the input data

In [53]:
prediction=classifier.predict(std_data)                               # predict the data
if(prediction[0]==1):
    print("Patient is diabetic")
else:
    print("Patient is not diabetic")

Patient is not diabetic